name: Home

on:
  workflow_dispatch:  # allows manual triggering
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - 'GNOME.md'
      - 'README.md'
      - 'notes/**'
      - '.git-crypt/**'
      - '.gitattributes'
      - '.gitignore'
      - 'system/**'
      - 'outputs/installation.nix'
      - 'outputs/nixos-conf.nix'
      - 'build'
      - 'switch'
      - '.mergify.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v18
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build Home Manager config 🏠"
        run: nix build

      - run: nix flake check
