---
name: Check Nix Flake

on:
  workflow_dispatch:  # allows manual triggering
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'system/**'
      - 'outputs/installation.nix'
      - 'outputs/nixos-conf.nix'
      - 'build'
      - 'switch'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Install Nix ❄️"
        uses: DeterminateSystems/nix-installer-action@main

      - name: "check nix flake"
        run: nix flake check --show-trace

      - name: "statix check"
        run: nix run nixpkgs#statix -- check
